version: "3.9"

services:
  code-red:
    build: .
    container_name: code-red
    ports:
      - 8000:8000
    volumes:
      - .:/code-red
    command: bash -c "cd ./output && python -m pelican.server"
    environment:
      - PYTHONUNBUFFERED=1
